### ISSUE TITLE
Proposal: new inenv

### ISSUE THREAD

**Issue by pnegahdar** [pnegahdar/inenv#35]
Inenv has proven useful. Proposing the following config to make it better going forward:

#### Config:

```toml
name = 'project1'
default_run_context = 'default'
project_root = 'projects/project1'
jump_root = 'projects/project1/app'

[[providers]]
	[[providers.python2]]
	deps = ['a==b', 'requirements.txt']
	activate = true
	auto_install = true
	watch_files = true

	[[providers.npm]]
	packages = ['package.json']
	watch_files = true
	auto_install = true
	yarn_install = true

[[run_context]]
name = 'default'
env_vars = {'PYTHONPATH': 1}
providers = ['python2', 'npm']

# Gbin like functionality
[[bin_dir]]
search_dirs = ['gbin/']
prefix = ""
run_context = '' # default

[[bin_file]]
name_override = ''
file = 'scripts/arc_run_test.py'


[[command]]
name = 'celery'
command = 'celery -A project -B'

[[command]]
name = 'runserver'
command = 'python manage.py runserver'
run_context = 'default' # Uses project by default


# Gitbook
[[docs]]
doc_dirs = ['docs/']


[[tmux]]
name = 'local-dev'
	[[tmux.windows]]
	title = 'Server'
	pane_cmds = [
		'runserver',
		'celery'
        ]
```

#### CLI:

Note: all of these commands would take a --rc (run_context) flag

```
inenv project1 -> activate
inenv projec1 tmux local-dev
inenv project1 bin test_projects
inenv project1 cmd lint
inenv project1 exec -- <cmd> 
inenv project1 docs (view|build)
inenv project1 jumproot
inenv project2 root
inenv autojump # toggle autojump
inenv install (project|--all)
```

#### Provider Implementation:

```python
class AbstractProvider(object):

	def __init__(project_name, config, inenv_root='.inenv'):
		self.project_name = project_name
		self.inenv_root = '.inenv'
		self.config = config

	def is_inited():
		pass

	def init():
		pass

	def activate():
		pass

	def deactivate():
		pass

	def watched_files():
		pass

	def run_watch_change(file_name):
		pass



class Python2Provider(abstract_env):
	pass
```
